package br.com.crearesistemas.service.impl.helper;

public enum CERCAS {
	DESCONHECIDO, FABRICA,
	FACTORY_CHECKPOINT_ENTRANCE1, FACTORY_CHECKPOINT_ENTRANCE2, FACTORY_CHECKPOINT_ENTRANCE3,
	FACTORY_CHECKPOINT_EMBED_ENTRANCE1, FACTORY_CHECKPOINT_EMBED_ENTRANCE2, FACTORY_CHECKPOINT_EMBED_ENTRANCE3,
	FACTORY_CHECKPOINT_EMBED_EXIT1, FACTORY_CHECKPOINT_EMBED_EXIT2, 
	ACESSO_PRIVADO, 
	ACESSO_PRIVADO_FABRICA, 
	CONTROLE_DE_ACESSO, VIADUTO, ACESSO_PRIVADO_ENTRADA_OU_SAIDA, 
	ENTRE_ACESSO_PRIVADO_SAIDA_E_VARRICAO, FILA, FILA_G1, PELOTAS_BALANCA_QUADRAS, PELOTAS_BARCACA_FILAS_VARRICAO, FILA_BARCACA_FABRICA, FILA_TRANSITO_FABRICA,
	FILA_INTERNA_FABRICA, FABRICA_MESAS, FABRICA_QUADRAS, PELOTAS_BARCACA, PELOTAS_FILAS, PELOTAS_QUADRAS, FABRICA_MESA_L100, FABRICA_MESA_L300, PORTO_RIOGRANDE, FABRICA_PATIO, PELOTAS_VARRICAO,
	BRACELL_LINHA2, BRACELL_LINHA1, BRACELL_BALANCA_LINHA2 , BRACELL_BALANCA_LINHA1;
	
}
